### ISSUE TITLE
[install][upgrade] Use Arch Linux archive

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#773]
For a more stable experience. This will help make sure the first-time setup and upgrade processes work as expected. Otherwise, they will break after a few months of Arch Linux upstream updates.

https://archive.archlinux.org/repos/

**Comment by LukeShortCloud** [comment]
There are about 40 packages that could potentially be installed during the first-time setup.

**Comment by LukeShortCloud** [comment]
https://archive.archlinux.org/repos/

**Comment by LukeShortCloud** [comment]
We cannot implement this until this upstream bug is fixed: https://github.com/LukeShortCloud/winesapOS/issues/802

**Comment by LukeShortCloud** [comment]
For Manjaro, there is this repository but (1) it does not have time stamped repositories only individual packages and (2) it only keeps the last 10 packages.

https://unix.stackexchange.com/questions/746362/manjaro-equivalent-for-the-arch-linux-archive-repository
https://manjaro.tuxboy.eu/

**Comment by GuestSneezeOSDev** [comment]
if manjaro repositories don't work you could use [endeavor os repository](https://github.com/endeavouros-team/repo/tree/master/endeavouros/x86_64)

**Comment by LukeShortCloud** [comment]
Hey @GuestSneezeOSDev , there are two large repositories we use for winesapOS outside of Arch Linux:

- Chaotic AUR = This contains thousands of pre-built AUR packages.
    - https://aur.chaotic.cx/
- winesapOS = We maintain this and have automated builds that get pushed out on the 15th of every month. If you're interested in how any of that works, here are all of the relevant links:
    - https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.0?tab=readme-ov-file#winesapos-repository
    - https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.0/CONTRIBUTING.md#build-packages-for-winesapos-repository
    - https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.0/scripts/repo/winesapos-build-repo.sh
    - https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.0/.github/workflows/repo-testing.yml

Thanks for linking the EndeavourOS repository! I had a quick look at it. We already provide some of those packages and don't need the rest.

---

This GitHub Issue is specifically to track using old/archived packages. Basically, we can pin Arch Linux to a specific date to guarantee that builds are reproducible. One problem I see a lot is that users will go through the first-time setup and some packages will fail to install due to upstream changes (for example: package conflicts, new dependencies, etc.). I've seen this problem happen as soon as 1 week after a new stable winesapOS release.

winesapOS supports builds based on Arch Linux and Manjaro. I recently added an additional GitHub Actions workflow for Manjaro which previously only received manual testing. You can find that at the top of our README.md file today. From over the years, I've found the Manjaro builds are much more stable than Arch Linux. However, in relation to this exact GitHub Issue, Arch Linux provides an official archive and Manjaro does not which is disappointing.

**Comment by LukeShortCloud** [comment]
I need to compare first-time setup and upgrade time differences between using the Arch Linux Archive versus using the fastest Arch Linux mirror.

**Comment by LukeShortCloud** [comment]
For the first-time setup in winesapOS 4.1.0-beta.0 on the minimal image, it took exactly 18 minutes for both the scenarios of (1) the fastest Arch Linux mirrors and (2) the Arch Linux Archive. I selected to install and do everything in the first-time setup. That is not too surprising. Most programs are installed as Flatpaks. I checked and exactly 10 packages can be installed via Pacman during the first-time setup. It is clear that we should use the Archive at least for that. There have been a few times were upstream package changes have broken our first-time setup.

**Comment by LukeShortCloud** [comment]
I have refactored the code to allow the `WINESAPOS_SINGLE_MIRROR*` to use the Arch Linux Archive (ALA). I did a quick test and found the non-archive build to take 9 minutes longer / 21% longer.

With ALA (`--env WINESAPOS_SINGLE_MIRROR=true --env WINESAPOS_SINGLE_MIRROR_URL=https://archive.archlinux.org/repos/2024/08/02`):

```
$ time sudo docker run --rm --env WINESAPOS_ENV_FILE=winesapos-env-minimal.sh --env WINESAPOS_SINGLE_MIRROR=true --env WINESAPOS_SINGLE_MIRROR_URL=https://archive.archlinux.org/repos/2024/08/02 -v $(pwd):/workdir -v /dev:/dev --privileged=true winesapos-img-builder:latest /bin/bash -x /workdir/scripts/winesapos-build.sh
real	42m30.050s
user	0m0.119s
sys	0m0.330s
```

Without ALA (`--env WINESAPOS_SINGLE_MIRROR=true`):

```
$ time sudo docker run --rm --env WINESAPOS_ENV_FILE=winesapos-env-minimal.sh --env WINESAPOS_SINGLE_MIRROR=true -v $(pwd):/workdir -v /dev:/dev --privileged=true winesapos-img-builder:latest /bin/bash -x /workdir/scripts/winesapos-build.sh
real	33m22.542s
user	0m0.115s
sys	0m0.343s
```

For keeping builds fast, I won't use ALA unless doing a release build.

**Comment by LukeShortCloud** [comment]
I did another test build with the ALA. It actually has a few failed package installs (seemingly different everytime). It's a slow server and normally we deal with that by having a XferCommand configured for Pacman. Unfortunately, that's broken right now.

Related: https://github.com/LukeShortCloud/winesapOS/issues/802

I'll defer this to the winesapOS 4.2.0 release instead.

**Comment by LukeShortCloud** [comment]
Here is the log from that ALA build when trying to install `plasma-meta`. I can confirm that `XferCommand` is the problem as our custom `wget` command deals with the "Operation too slow" errors by being more patient and allowing for download retries.

```
error: failed retrieving file 'noto-fonts-1:24.8.1-1-any.pkg.tar.zst.sig' from archive.archlinux.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

**Comment by LukeShortCloud** [comment]
We won't use the ALA for builds but I'll at least document how to use it.
