### ISSUE TITLE
[install][setup] Support PS4 and PS5 game streaming

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#867]
Install the chiaki4deck project to allow streaming PS4 and PS5 games from the video game console to Linux.

https://github.com/streetpea/chiaki4deck

**Comment by LukeShortCloud** [comment]
The project was renamed last night from chiaki4deck to chiaki-ng.

https://www.gamingonlinux.com/2024/07/playstation-remote-play-app-gets-renamed-to-chiaki-ng-chiaki-next-generation/

**Comment by GuestSneezeOSDev** [comment]
Use the `appimage` of the app

**Comment by LukeShortCloud** [comment]
As of the latest v1.9.0 release of chiaki-ng, there is now a Flatpak! This will be even easier to manage.

https://github.com/streetpea/chiaki-ng/releases/tag/v1.9.0
