### ISSUE TITLE
[install][setup] Add game streaming server support

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#868]
Install game streaming support by having Moonlight for a client and Sunshine as a server.

**Comment by GuestSneezeOSDev** [comment]
Those are packages in the AUR maybe use
```
yay_install_chroot moonlight \
sunshine \
```

**Comment by LukeShortCloud** [comment]
This is why I love Arch Linux. There are so many great packages on the AUR. :-)

I looked into if any are hosted on the Chaotic AUR repository. They technically both are but Sunshine is an older version. Apparently there was some drama relating to the project maintainer. Either way, we can also host newer packages on the winesapOS repository.

I'll look into adding these.

**Comment by GuestSneezeOSDev** [comment]
For sunshine run : 

```bash
wget https://github.com/LizardByte/Sunshine/releases/download/v2024.809.202917/sunshine.pkg.tar.zst
pacman -U sunshine.pkg.tar.zst
```

**Comment by LukeShortCloud** [comment]
Nice, I'll add that. Thank you for the hint!

**Comment by LukeShortCloud** [comment]
Apparently both Moonlight and Sunshine have Flatpaks. I'll go ahead and add those.

https://github.com/moonlight-stream/moonlight-qt/releases
https://github.com/LizardByte/Sunshine/releases
