### ISSUE TITLE
[install] Allow installing the COSMIC DE

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#870]
The COSMIC DE from System76 and used in their upcoming Pop!_OS 24.04 release, is about to have its first alpha. It can be installed on Arch Linux by install the `aur/cosmic-epoch-git` meta package. The Chaotic AUR said that they will provide all of those packages once the desktop environment is more stable.

`https://github.com/chaotic-aur/packages/issues/2397`

Our default will remain KDE Plasma but developers will have the option to install COSMIC DE instead.

**Comment by GuestSneezeOSDev** [comment]
why not install it with the yay package?

**Comment by GuestSneezeOSDev** [comment]
I added it to my PR and OS (which is now based on winesapOS)

**Comment by LukeShortCloud** [comment]
Thanks! I was just waiting for the project to mature yet. The first alpha of COSMIC DE has not even launched yet. I'd like to have it installable when it is in beta. The ChaotiC AUR should have the packages shipped for it eventually. In any case, this is a goal to add for winesapOS 5.0.0.

Thanks to your recent commit to the PR, I noticed that the name of the meta package was recently changed from `cosmic-epoch-git` to `cosmic-session-git`. The problem with just building that one package is that it actually has a lot of other AUR dependencies that also need to be built. 16 required dependencies are from the AUR. Another 5 dependencies from the AUR are optional. We would need to pre-build all of those packages. Otherwise, build times for winesapOS would take a long time as the desktop environment has to be built from scratch.

**Comment by GuestSneezeOSDev** [comment]
Building winesapOS is very long it took for me >1.5 Hours usually and i do not want to extend the time for it to build

**Comment by LukeShortCloud** [comment]
We have a caching feature in the build but it's broken because Pacman is broken. Once I have a workaround, I can share additional instructions to help your builds go faster.

**Comment by GuestSneezeOSDev** [comment]
Thank's

**Comment by LukeShortCloud** [comment]
COSMIC now has packages in the Chaotic AUR which is nice. However, I don't want to ship the `*-git` packages. The stable release of COSMIC is coming out later this year. We can wait for that.

https://github.com/chaotic-aur/packages/commit/4d80c90bb6f7d1e7f1952ea292c02a7f070935eb
https://www.phoronix.com/news/System76-COSMIC-Alpha

**Comment by LukeShortCloud** [comment]
Wow, this is unexpected: Arch Linux has promoted all COSMIC desktop environment packages from the AUR to the Extra repository. The initial 1.0.0.alpha.1-1 version of all packages are available to install using Pacman.

**Comment by LukeShortCloud** [comment]
I wasn't originally planning on adding this feature so soon. COSMIC is still in Alpha (Alpha 2, currently) and I'm waiting for desktop shortcuts to be implemented (which was promised to happen before the stable release). However, I've been testing other desktop environments in terms of performance. COSMIC is a lot faster than KDE Plasma. I haven't done any real benchmarks but it feels a lot more responsive and appears to be faster at loading. One common complaint is that KDE Plasma is slow and I've heard a few users voice in the past that they would prefer we switch back to Cinnamon because it's faster. It's heavy work-in-progress support for Wayland makes me a bit hesitant to do that. Defaulting to COSMIC when it's stable is more likely as it was developed with Wayland in mind from the ground-up.
