### ISSUE TITLE
[install] Create gamescope-session-wine-desktop

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#884]
This is a wild idea I had: use Wine as your actual desktop environment. Experience Windows without Windows. This should technically be possible with the help of gamescope-session. Maybe another compositor would be better, though. I need to do more research into this.

**Comment by GuestSneezeOSDev** [comment]
Maybe i can help I have never made my own DE but i could learn how to

**Comment by LukeShortCloud** [comment]
A fundamental problem with this is that Wine has no concept of how to manage windows with Gamescope. It would be better to use Sway to launch the virtual Wine desktop instead.
