### ISSUE TITLE
[install] Support Windows Vista-era PCs

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#885]
I'm honestly not sure how we can support older PCs. I have an old PC with Windows XP that supports 64-bit operating systems but I could never get winesapOS to boot on it. Other Linux distributions work including the official Arch Linux ISO installer.

Converting from the partition table format from GPT to MBR does not work. I also looked into a hybrid of MBR and GPT and, although it is possible, it is not recommended. `"WARNING! Hybrid MBRs are flaky and dangerous!"`

https://wiki.gentoo.org/wiki/Hybrid_partition_table

We also support both legacy BIOS and UEFI boot. I can confirm via virtual machines that both separately work.

At the end of the day, I'm not sure I even want to support this use-case. winesapOS was meant to be portable and most early 2000s PCs cannot even boot from USB. winesapOS is also a bit resource intensive compared to other Linux distributions like Puppy Linux.

Related: https://github.com/LukeShortCloud/winesapOS/issues/627

**Comment by GuestSneezeOSDev** [comment]
Add CD/DVD support this will require an ISO archive instead of IMG

**Comment by LukeShortCloud** [comment]
When I last tested, I was using internal drives (since USB boot does not work on these really old PCs) with the winesapOS IMG files and that was not working. It works on modern computers and in virtual machines.

Running winesapOS as a live CD/DVD was intentionally not a goal for our project (although we could use a live CD/DVD for an installer, the fact remains that winesapOS still does not run on this hardware).

**Comment by GuestSneezeOSDev** [comment]
Maybe when we complete `live image installer` we can then continue with this issue

**Comment by GuestSneezeOSDev** [comment]
I Will make an unofficial `winesapOS` archiso config which will allow us to make the Live Image Installer

**Comment by LukeShortCloud** [comment]
I was hoping that by using a label to boot, it might help fix Windows XP-era booting. It did not.

Related: https://github.com/winesapOS/winesapOS/issues/935

**Comment by LukeShortCloud** [comment]
I tested using MBR instead of GPT for the partition scheme. It did not work. I also tested changing the `boot` partition flag to the actual `/boot` partition and that also did not work.

Also, for reference, the oldest computer I have that I am testing with is actually a Windows Vista computer.

I wonder if Ventoy could be used as a workaround since we support it now.

**Comment by LukeShortCloud** [comment]
The code was minimal so I kept the ability to build with MBR instead of GPT. Even though it does not help this issue, it could still be related to the final fix.

**Comment by LukeShortCloud** [comment]
I tested Ventoy 1.0.99 with winesapOS 4.2.0 and my old computer still does not boot.

**Comment by LukeShortCloud** [comment]
At this point, I might just recommend users to use Slax (with the Debian base) instead of winesapOS for older computers. It'll have better performance anyways since winesapOS is a bit heavier in terms of resource usage.

**Comment by GuestSneezeOSDev** [comment]
> At this point, I might just recommend users to use Slax (with the Debian base) instead of winesapOS for older computers. It'll have better performance anyways since winesapOS is a bit heavier in terms of resource usage.

winesapOS Debian Image type :trollface:

**Comment by LukeShortCloud** [comment]
Ironically, Debian 13 Trixie Alpha 1 was just released dropping support for 32-bit processors. I updated our recommendation to still be for Slax for legacy PCs but to use the Slackware variant instead of Debian.

https://www.phoronix.com/news/Debian-Installer-Trixie-Alpha-1
