### ISSUE TITLE
[repo] aw87559-firmware fails to build

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#911]
Good news: the new `linux-firmware-valve-20231113.1-2-any.pkg.tar.zst` builds perfectly!

Bad news: unrelated but the `aw87559-firmware` package fails to build.

https://github.com/LukeShortCloud/winesapOS/actions/runs/10276397386/job/28436742093

_Originally posted by @LukeShortCloud in https://github.com/LukeShortCloud/winesapOS/issues/910#issuecomment-2272531987_

**Comment by LukeShortCloud** [comment]
I found the issue (incorrect download URL) and reported it to the upstream maintainer of the AUR package: https://aur.archlinux.org/packages/aw87559-firmware#comment-985532

**Comment by GuestSneezeOSDev** [comment]
Comment it for now until it gets fixed similar to FATX

**Comment by LukeShortCloud** [comment]
If this isn't fixed in the AUR within a week, I'll fork the AUR git repository and patch it for winesapOS. This will help with adding audio support for some AYANEO devices and the new Orange Pi handheld from Manjaro.

**Comment by LukeShortCloud** [comment]
For FATX, I ended up hardcoding the installation of the package from an old winesapOS repository.

https://github.com/LukeShortCloud/winesapOS/blob/1837184b47badf8efc3bd9e778c43b71c369ffd1/scripts/winesapos-install.sh#L676

Unfortunately, this `aw87559-firmware` package is so new I don't even have an older version of it built.

**Comment by LukeShortCloud** [comment]
Actually, I was looking in the wrong place (at old archives of the `winesapos-testing` repository). The latest one does have the package which we can re-use.

https://winesapos.lukeshort.cloud/repo/winesapos-testing/x86_64/aw87559-firmware-8.0.1.10-1-x86_64.pkg.tar.zst

**Comment by LukeShortCloud** [comment]
I put in a temporary workaround for the winesapOS 4.1.0 release.

**Comment by LukeShortCloud** [comment]
This does not seem to be getting fixed upstream anytime soon. We already have a workaround in place for winesapOS. Closing as resolved.
