### ISSUE TITLE
[setup] Improve the locale UX

### ISSUE THREAD

**Issue by Trinki79** [winesapOS/winesapOS#943]
Hi, I just installed your distribution, but I can't change the language, only English, American and Chinese are 
![kde](https://github.com/user-attachments/assets/8033ffd4-e4f2-45d6-8c61-c9d0191197fb)
available.[

**Comment by GuestSneezeOSDev** [comment]
Which language would you like to use in winesapOS? I'd be happy to help you with any of your issues 😄

**Comment by LukeShortCloud** [comment]
@Trinki79 The winesapOS first-time setup itself is only in English but it should allow you to change the locale (which changes the language, calendar, printer settings, etc.) for other supported apps. I'm not sure why KDE Plasma won't let you change it.

Run the "winesapOS First-Time Setup" desktop shortcut, say no or cancel to everything until you get to this question:

"Do you want to change the current locale (en_US.UTF-8 UTF-8)?"

Input this locale: `it_IT.UTF-8`

Then continue to say no or cancel through the rest of the first-time setup until it tells you to reboot. Then reboot.

Let me know if that works or not!

**Comment by Trinki79** [comment]
ok I'll try it tomorrow and let you know

**Comment by LukeShortCloud** [comment]
I was slightly wrong. The locale you'll want to use is: `it_IT.UTF-8 UTF-8`

Hopefully that works for you tomorrow!

**Comment by Trinki79** [comment]
Thanks, I solved it, I did as you told me and it worked. Maybe for subsequent versions you can manage this configuration better. Thanks again for the help.

**Comment by LukeShortCloud** [comment]
Glad to hear it's working now!

I agree, we'll look into improving this process as it's not very intuitive.
