### ISSUE TITLE
[install] Fix audio stutter

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#956]
Despite Linux 6.12 having real-time support, it still needs the kernel argument `preempt=full` to fix audio stuttering issues on some systems.

https://www.phoronix.com/news/Linux-6.12-Does-Real-Time
https://www.reddit.com/r/linux/comments/1fl88vk/comment/lonvpgv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by GuestSneezeOSDev** [comment]
The Linux kernel updates daily meaning a solution will happen in a week or so

**Comment by LukeShortCloud** [comment]
Yeah, it's specifically 6.12.0-rc0 which was reported as not working properly. Hopefully it'll be fixed in 6.12.0-rc1 or at least before the 6.12.0 stable release.

**Comment by LukeShortCloud** [comment]
I have not  seen anyone else report any issues with audio in Linux 6.12. I'll go ahead and close this out. winesapOS 4.2.1 or 4.3.0 will include Linux >= 6.12.
