### ISSUE TITLE
[setup] Allow passwordless login

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#965]
For non-secure images (on the minimal and performance images only), use PAM to create a truly passwordless experience. This is especially helpful for handheld devices. If not making the default setting during a winesapOS build, perhaps make it an option in the first-time setup.

Refer to: `https://github.com/sddm/sddm/issues/751#issuecomment-2087796021`

**Comment by GuestSneezeOSDev** [comment]
`https://github.com/sddm/sddm/pull/1368`

**Comment by LukeShortCloud** [comment]
Nice! That pull request you linked provides all of the details I need to implement this.

I'm a bit frustrated because this insecure workaround is not needed on LightDM. The primary reason I switched from LightDM to SDDM was for Wayland support as we eventually phase out Xorg. Since this is a big security concern (it makes it so users could login to SSH without a password or key, for example), I'll probably make this part of the first-time setup and disable it for users using our default settings.
