### ISSUE TITLE
[install] Remove oxp-sensors-git

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/winesapOS#996]
Once Linux 6.12 is promoted to LTS (which includes a huge update to the amount of supported devices), we can rely on the native kernel's `oxp-sensors` module instead of `oxp-sensors-git`. My friend Derek helped lead development on this. Kudos to him and everyone else who have been working on this!

https://www.gamingonlinux.com/2024/11/linux-kernel-6-12-is-out-now-with-real-time-capabilities-more-gaming-handheld-support/
https://docs.kernel.org/hwmon/oxp-sensors.html

**Comment by GuestSneezeOSDev** [comment]
Comment this line https://github.com/winesapOS/winesapOS/blob/main/scripts/winesapos-install.sh#L1079
